# Generated by Django 4.1.5 on 2023-01-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_answer_choice_alter_answer_multiple_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.choice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='multiple_choices',
            field=models.ManyToManyField(blank=True, to='main.multiplechoice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, to='main.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='multiple_choices',
            field=models.ManyToManyField(blank=True, to='main.multiplechoice'),
        ),
    ]
